import { Inter } from "next/font/google";
import "./globals.css";
import { getUser } from "./actions/auth/actions";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { session } = await getUser();
  return (
    <html lang="en">
      <body className={inter.className}><NavBar auth={session !== null} />{children}</body>

    </html>
  );
}
