import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { getServerAuthSession } from "@/auth";
import { AuthProvider } from "@/components/Provider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerAuthSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar auth={session !== null} />
        <AuthProvider>{children}</AuthProvider>
        <Toaster position="top-left" />
      </body>
    </html>
  );
}
